setTimeout(function () { console.log("hi") }, 1000)
setTimeout(function () { console.log("hi") }, 1000)
setTimeout(function () { console.log("hi") }, 1000)
setTimeout(function () { console.log("hi") }, 1000)
setTimeout(function () { console.log("hi") }, 1000)